### ISSUE TITLE
交替优化机制和GRL梯度翻转层

### ISSUE THREAD

**Issue by songyonger** [zhengli97/CTKD#1]
您好，请问交替优化机制和GRL梯度翻转层在代码里的哪处呢？

**Comment by zhengli97** [comment]
交替优化在`train_student.py line 297, 311, 379`以及`helper.loops.py line 73`起始 将这个module加入到sgd的训练中在bp的时候会交替优化。
梯度反向在`./models/temp_global.py line 21`。给负的lambda_值就是在梯度反向

**Comment by songyonger** [comment]
不好意思，还是有一点疑惑，loops.py里不是model_s和mlp参数一块进行优化的吗？

**Comment by zhengli97** [comment]
代码实现上是一起优化的，是因为我把grl直接跟mlp写在一起了。术语上的描述是交替优化的，因为mlp是在得到stu的梯度之后才开始优化自己。也就是stu先优化了，梯度到了mlp，然后mlp再反向梯度优化。

**Comment by zhengli97** [comment]
不客气 如果觉得这个repo有帮助 还请点个star~
