### ISSUE TITLE
您好，不好意思，我在您的代码中没有找到instance-τ的相关代码，请问可以分享一下吗？

### ISSUE THREAD

**Issue by Senqi-Guan** [zhengli97/CTKD#12]
我在您提供的代码中只看到了global-T的实现，并没有找到instance-τ具体是怎么做的。可能是您忘了上传吗？或者是我没有找到？请问可以提供一下吗？

**Comment by zhengli97** [comment]
同学你好，当时这段代码并没有提供在repo里面。我刚才已经上传到云盘里，里面有模型文件和训练log，详情请check一下README里面的内容哈，我重新更新了云盘链接放在了里面。

**Comment by Senqi-Guan** [comment]
好嘞，感谢您的回复！
