### ISSUE TITLE
请问怎么用于目标检测的呢？

### ISSUE THREAD

**Issue by ufestkc** [zhengli97/CTKD#15]
你好，分类里是用教师学生的logit蒸馏，目标检测里用的是？如果不是用的logit那么哪里还会涉及到温度T呢？

**Comment by zhengli97** [comment]
跟dkd用在detection里面的方式是一样的，dkd里也有temp，就把里面的temp换成CTKD就行了。

**Comment by ufestkc** [comment]
明白了谢谢

**Comment by ZhenboZhao77** [comment]
请问再检测中temp换CTKD是怎么实现的，能不能给一个例子？
