### ISSUE TITLE
关于temp更新

### ISSUE THREAD

**Issue by JINzezhong7** [zhengli97/CTKD#16]
您好，非常感谢您可以开源代码，我有一个问题，关于temp更新opt.t_start + opt.t_end * torch.sigmoid(temp)，这样做是为什么呢。以及t_start 和 t_end 选取 有什么特别的地方吗

**Comment by zhengli97** [comment]
用sigmoid是为了归一化，让模型更好训，最终值的范围为[0,1]。opt.t_start是起始偏移量，给定一个固定的temp下限。opt.t_end是缩放参数，以固定倍数对经过了归一化的值进行缩放。这样的一套参数下来，就会把temp约束在[t_start, t_start+t_end]的范围内

**Comment by JINzezhong7** [comment]
我发现第一轮 temp基本已经增大到t_start + t_end 的附近了，请问这是正常的吗

**Comment by zhengli97** [comment]
不正常 说明没收敛。正常的情况你可以参考提供的训练日志的情况

**Comment by JINzezhong7** [comment]
您好，我在应用dkd的时候也遇到了相同的问题，loss一下子就变成nan。您可以提供一下您优化dkd的完整log吗我参考一下

**Comment by zhengli97** [comment]
其实在readme里的baidu网盘里已经提供了

**Comment by JINzezhong7** [comment]
请问有没有每一个iter的log那种更详细一些的，因为我的log也是第一个epoch的第二个iter就变成nan了，后续一直是nan

**Comment by zhengli97** [comment]
是

**Comment by JINzezhong7** [comment]
关于instance ctkd，我想问一下mlp层两层 ，是两层linear层吗（batch+relu+linear）。您中间层的hidden dim设置的是多少呢
，非常期待您的回答

**Comment by zhengli97** [comment]
readme里面有

**Comment by zhengli97** [comment]
Hi 同学 没有问题的话 我就关闭这个issue了哈

**Comment by JINzezhong7** [comment]
您好，我发现我的temp并不是像论文中的抖动变化，是从一个很高的值经过几轮之后下降到1.几 然后缓慢下降，在最后的几轮缓慢上升，请问这是收敛了吗

**Comment by zhengli97** [comment]
嗯 看情况是的
