### ISSUE TITLE
出现nan值，一开始temp就是15.6212，之后就变成nan

### ISSUE THREAD

**Issue by smalltoyfox** [zhengli97/CTKD#17]
感谢您出色的开源工作，我尝试将您的工作加入了我的知识蒸馏网络中，但是在一开始为15.6212之后就一直出现nan值。
我是直接调用了Global_T，然后在训练中计算了decay_value，然后通过
temp = self.CTKD(student_preds,teacher_preds, cos_value)
        temp = t_start + t_end * torch.sigmoid(temp)
        temp = temp.cuda()
        temp = temp.mean()
计算temp，将temp直接传递给蒸馏损失函数，请问这个流程有问题吗？

**Comment by zhengli97** [comment]
你参考一下issue 9的解决方法 https://github.com/zhengli97/CTKD/issues/9

**Comment by zhengli97** [comment]
我想问一下 最后问题解决了吗

**Comment by smalltoyfox** [comment]
最后并没有解决这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zheng Li ***@***.***&gt;
发送时间: 2024年4月27日 20:54
收件人: zhengli97/CTKD ***@***.***&gt;
抄送: smalltoyfox ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhengli97/CTKD] 出现nan值，一开始temp就是15.6212，之后就变成nan (Issue #17)





 
我想问一下 最后问题解决了吗
