### ISSUE TITLE
蒸馏损失一直不下降

### ISSUE THREAD

**Issue by zswzswzsw233** [zhengli97/CTKD#18]
您好，我想在论文「Channel-wise Knowledge Distillation for Dense Prediction」提出的通道蒸馏中加入您的对抗蒸馏，现在发现蒸馏损失较大且一直不下降，是否应该将默认的t_end=20调小？

**Comment by zswzswzsw233** [comment]
损失会上升下降但整体是在上升

**Comment by zhengli97** [comment]
在训练的过程里面，温度t有收敛下来吗

**Comment by zswzswzsw233** [comment]
> 在训练的过程里面，温度t有收敛下来吗

训练过程较长，观察了两个epoch，t好像不收敛

**Comment by zswzswzsw233** [comment]
> > 在训练的过程里面，温度t有收敛下来吗
> 
> 训练过程较长，观察了两个epoch，t好像不收敛

如果t_end=20，前两轮都是16左右

**Comment by zhengli97** [comment]
temp没往下降的话，一般要先考虑这个，看看训练到最后会不会降下来
