### ISSUE TITLE
关于可学习温度模块

### ISSUE THREAD

**Issue by chengqb0126** [zhengli97/CTKD#19]
老师，您好！您的工作非常棒，对我启发很大。但我现在对您论文中的可学习温度模块里的Global-T和Instance-T产生了疑问。Instance-T这个方法用到了您论文所说的对抗性学习吗？以及Global-T图中可学习参数就是论文中的对抗性学习吗？原谅我的冒昧打扰，期望您的回复，不胜感激！

**Comment by zhengli97** [comment]
(1)用到了。(2)可学习参数不是对抗性学习，对抗的发挥是在grl上
