### ISSUE TITLE
Instance-T

### ISSUE THREAD

**Issue by ZhenboZhao77** [zhengli97/CTKD#21]
你好作者！
非常有意义的工作，但是我在阅读代码实现时仅仅发现了Global-T的实现（models/temp_global.py）
但是并没有发现 Instance-T的实现，论文中讲这种温度调整方法效果会更好请问有没有具体实现的代码呢？
感谢！

**Comment by zhengli97** [comment]
仔细看看readme

**Comment by ZhenboZhao77** [comment]
嘿嘿，
感谢！
