### ISSUE TITLE
instant-T算法在哪

### ISSUE THREAD

**Issue by yuzhi535** [zhengli97/CTKD#5]
您好，请问一下，instance-T算法在代码的何处呢？我没找到。

**Comment by zhengli97** [comment]
暂时没有release instance-T的代码。你可以留下邮箱或者发邮件给我 zhengli97@qq.com，我发模型文件给你。

**Comment by yuzhi535** [comment]
邮箱：kurisu@outlook.sg 
谢谢大佬！
