### ISSUE TITLE
DALI error

### ISSUE THREAD

**Issue by Luadoo** [zhengli97/CTKD#6]
![image](https://github.com/zhengli97/CTKD/assets/58927660/6ae828cf-cf6a-4306-881d-bde8b0c0943f)

大佬，我这刚刚复现就出现这个错误，我对比看了下student和teacher有个什么duplicate，但是我找了半天没发现什么对方错了，请帮我回答下，多谢！

**Comment by zhengli97** [comment]
没有dali就把跟这些相关的code注释掉就行了 不影响最终结果

**Comment by Luadoo** [comment]
您能不能具体说下注释掉哪一块，我是把相关联的有dali那段都注释了，但是还是报错了；就是你的代码跟SimKD很多相似的,好像部分工作是源自那里，可是我看SimKD很简单直接就能复现出来，也用了dali呢

**Comment by zhengli97** [comment]
1. 注释掉dali之后有bug请报告bug情况
2. 我没装dali 所以code都删了 部分源代码确实源于SimKD

**Comment by zhengli97** [comment]
刚才把dali在train_teacher.py里面删掉了 你可以重新clone一下code试试看

**Comment by Luadoo** [comment]
您好，我试了下用 sh scripts/run_cifar_vanilla.sh 就出现这个报错：

![image](https://github.com/zhengli97/CTKD/assets/58927660/6e058d56-b8aa-43da-bcf0-8dd80bceb8f5)

然后我开始单独从scratch训练教师模型又报错：
![image](https://github.com/zhengli97/CTKD/assets/58927660/15988db5-3253-453f-b531-0151dc59181b)

**Comment by Luadoo** [comment]
![image](https://github.com/zhengli97/CTKD/assets/58927660/c1b09763-6002-4e4f-a17e-27103067be2e)
然后少这个数据库我也pip install imgaug后好像就跟上次一样，一直跟你那个imagenet.py文件有关联似的，上次一开始也这样，我没搞明白我训练cifar100为啥非跳到Imagenet上去

**Comment by zhengli97** [comment]
1. train_teacher.py里面确实有bug。你可以直接用我给的pre-trained teacher来训。我改一下这个bug。当时在服务器端写code跑实验验证的时候开源忘记改回来了。这个'feat_drop_ratio'确实是我没注意到。
2. 你先用提供的pre-trained来做验证吧

**Comment by zhengli97** [comment]
已经fix了train_teacher.py里面的bug

**Comment by Luadoo** [comment]
这样啊，我有个想法就是我把SimKD的CIFAR100上的教师模式全自己训练出来了，我直接放到CTKD teacher该存储的位置下能不能就算用上，我感觉都一样，因为我在国外来着，百度云没有手机验证没法登陆，或者你可以加我GITHUB主页有我的微信加下细说，大佬方便的话！

**Comment by zhengli97** [comment]
train_teacher.py跟simKD里面的code是一样的 训出来的weight和py文件对得上能load进来就行

**Comment by Luadoo** [comment]
好的，我在试试，有问题回头再请教老哥！

**Comment by Luadoo** [comment]
jiexu2017action@gmail.com  感谢！

**Comment by Luadoo** [comment]
老兄，working了已经！后续有问题还请多多指教！

**Comment by zhengli97** [comment]
> [jiexu2017action@gmail.com](mailto:jiexu2017action@gmail.com) 感谢！

有预训练模型的邮件已经发过去了。注意查收。

> 老兄，working了已经！后续有问题还请多多指教！

ok 后面有问题欢迎邮件或者提issue。如果觉得repo有帮助 还请麻烦点个star支持一下哈哈~
