### ISSUE TITLE
temp在一次backward后，就从15.6212变成了nan

### ISSUE THREAD

**Issue by ufestkc** [zhengli97/CTKD#9]
你好，我是将你们code里跟temp有关的部分替换了我自己的蒸馏方法里的温度，在第一次loss.backward后，temp的值从15.6212变成了nan，且一直是nan，请问有什么问题或建议吗

**Comment by zhengli97** [comment]
可以尝试改小λ的值？用较低的值去试试看会不会收敛

**Comment by ufestkc** [comment]
> 可以尝试改小λ的值？用较低的值去试试看会不会收敛

我发现是因为引入了dkd的loss，去掉dkd loss就能正常收敛。然后我看run_cifar_distill.sh里beta设为0，也是因为这个吗（但我把dkdloss的权重也设为0也是nan，反之只要总的loss里有dkdloss就不行）

**Comment by zhengli97** [comment]
run_cifar_distill.sh里面是alpha设成0，beta设成1的

**Comment by JINzezhong7** [comment]
请问解决了吗，我也遇到了这个问题，也是一下就变成nan

**Comment by ufestkc** [comment]
> 请问解决了吗，我也遇到了这个问题，也是一下就变成nan
损失函数里的KL散度里，分母那一项（好像是教师logits）加上一个1e-10就行，只是不知道为什么分母会变0

**Comment by zhengli97** [comment]
加上了这个之后的temp收敛下来了吗？大概值的范围是多少？

**Comment by JINzezhong7** [comment]
请问具体是在哪里加呢，
<img width="1038" alt="image" src="https://github.com/zhengli97/CTKD/assets/131787594/f0c4958b-ed17-454f-bce0-a768de5ab077">
是nckd那里还是tckd那里

**Comment by ufestkc** [comment]
对收敛了，范围忘了，应该差不多的

**Comment by ufestkc** [comment]
> 请问具体是在哪里加呢， <img alt="image" width="1038" src="https://private-user-images.githubusercontent.com/131787594/320856832-f0c4958b-ed17-454f-bce0-a768de5ab077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzE0MzksIm5iZiI6MTcxMjY3MTEzOSwicGF0aCI6Ii8xMzE3ODc1OTQvMzIwODU2ODMyLWYwYzQ5NThiLWVkMTctNDU0Zi1iY2UwLWE3NjhkZTVhYjA3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMzU4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWZkNmI1MzUxNzdmYTJkNTZhZjhlZjlkMTMwMmQ5NTJiNjM4NTFlYzM1YzcyZGRlZjRjODUxODZlMDhjMDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZgtMx1dKtFO8T2R81fN6OxDsdBN7w6HpvLerDdux5TM"> 是nckd那里还是tckd那里

好像是两个地方都要，你试试吧

**Comment by zhengli97** [comment]
好嘞 谢谢你的反馈 我后面会把这个更新到QA里
